# Check out https://docs.codemagic.io/getting-started/yaml/ for more information

workflows:
  flutter-package:
    name: morse_translator
    environment:
      flutter: beta
    scripts:
      - name: Switch to Dart beta
        script: |
          dart --version
      - name: Static analysis
        script: |
          dart analyze
      - name: Testing
        script: |
          dart test
      - name: Publishing
        script: |
          pub publish --dry-run
