# Check out https://docs.codemagic.io/getting-started/yaml/ for more information

workflows:
  flutter-package:
    name: morse_translator
    environment:
      flutter: beta
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - name: Switch to Dart beta
        script: |
          brew unlink dart
          brew install dart-beta
          dart --version
      - name: Testing
        script: |
          dart test
      - name: Static analysis
        script: |
          dart analyze
    publishing:
      scripts:
        - name: Check for publishing
        script: |
          pub publish --dry-run
