# Check out https://docs.codemagic.io/getting-started/yaml/ for more information

workflows:
  flutter-package:
    name: morse_translator
    environment:
      flutter: beta
    cache:
      cache_paths:
        - $FLUTTER_ROOT/.pub-cache
    scripts:
      - name: Switch to Dart beta
        script: |
          brew unlink dart
          brew install -f dart
      - name: Get packages
        script: |
          flutter pub get
      - name: Static analysis
        script: |
          flutter analyze
      - name: Testing
        script: |
          flutter test
      - name: Publishing
        script: |
          flutter pub publish --dry-run
