name: morse_translator
description: A dart library for morse encryption and decryption
version: 1.1.0-nullsafety.0
homepage: https://github.com/sbis04/morse_translator

environment:
  sdk: '>=2.12.0-133.2.beta <3.0.0'

dependencies:
  test: ^1.16.0-nullsafety.13
  characters: ^1.1.0-nullsafety.5
  collection: ^1.15.0-nullsafety.4
